# üêº Pandas Practice: DataFrames, Selection, Mapping, and More

In [19]:
import pandas as pd
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Sample data
names = ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan', 'Fiona', 'George', 'Hannah']
departments = ['Sales', 'Marketing', 'HR', 'Tech']

# Create a DataFrame
df = pd.DataFrame({
    'Name': np.random.choice(names, size=20),
    'Age': np.random.randint(22, 60, size=20),
    'Department': np.random.choice(departments, size=20),
    'Salary': np.random.randint(40000, 120000, size=20),
    'YearsExperience': np.random.randint(0, 20, size=20)
})
df.head()

      Name  Age Department  Salary  YearsExperience
0   George   43         HR   75920               15
1    Diana   23  Marketing  107121               12
2    Ethan   45       Tech  109479               17
3   George   51      Sales   59457               14
4  Charlie   59       Tech  106557               12

# üß™ PRACTICE QUESTIONS BELOW


# 1Ô∏è‚É£ Use .loc to select all rows where the Department is 'Tech'.
#    - Describe what .loc does and why it's useful for label-based filtering.

In [20]:
# .loc acsesses the dataframe using labels wheather thye row labels or columns it slices the dataframe returning a subset df
df[df.loc[:, 'Department'] == 'Tech']

       Name  Age Department  Salary  YearsExperience
2     Ethan   45       Tech  109479               17
4   Charlie   59       Tech  106557               12
12  Charlie   49       Tech  111211               11
13  Charlie   37       Tech  105697                7
15    Ethan   24       Tech   72606               18
17   Hannah   28       Tech   80397                7
19  Charlie   30       Tech   95591                2


# 2Ô∏è‚É£ Use .iloc to select the first 5 rows and the last two columns.
#    - What is the difference between .loc and .iloc?

In [21]:
# The diffrence between loc and iloc is that loc takes the lacation label while the iloc takes the lpcation index
df.iloc[:5,-2:]

   Salary  YearsExperience
0   75920               15
1  107121               12
2  109479               17
3   59457               14
4  106557               12


# 3Ô∏è‚É£ Map a new column called 'DeptCode' where:
#     'Sales' -> 1, 'Marketing' -> 2, 'HR' -> 3, 'Tech' -> 4.
#    - Use .map and explain what happens if a value is not mapped.

In [22]:
df['DeptCode'] = df['Department'].map({'Sales' : 1, 'Marketing' : 2,
                                       'HR' : 3, 'Tech' : 4})
df.head()
# if a i passed to the map a dep that is not in the df it will assign NAN to it

      Name  Age Department  Salary  YearsExperience  DeptCode
0   George   43         HR   75920               15         3
1    Diana   23  Marketing  107121               12         2
2    Ethan   45       Tech  109479               17         4
3   George   51      Sales   59457               14         1
4  Charlie   59       Tech  106557               12         4


# 4Ô∏è‚É£ Use .apply to calculate a new column 'Seniority' where:
#     - If YearsExperience > 10 ‚Üí 'Senior'
#     - If between 5-10 ‚Üí 'Mid-Level'
#     - Else ‚Üí 'Junior'
#    - Use a lambda function with apply.

In [23]:
df['Seniority'] = df['YearsExperience'].apply(lambda x : 'Senior' if x>=10
                                              else('Mid-level' if  x<10 and x>=5
                                                   else 'Junior'))
df.tail()

       Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
15    Ethan   24       Tech   72606               18         4     Senior
16    Diana   58         HR   51534               16         3     Senior
17   Hannah   28       Tech   80397                7         4  Mid-level
18   Hannah   42      Sales   41016                2         1     Junior
19  Charlie   30       Tech   95591                2         4     Junior


# 5Ô∏è‚É£ Overwrite all salaries for employees with < 3 years of experience to 35000.
#    - Use boolean indexing with .loc to do this.

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             20 non-null     object
 1   Age              20 non-null     int64
 2   Department       20 non-null     object
 3   Salary           20 non-null     int64
 4   YearsExperience  20 non-null     int64
 5   DeptCode         20 non-null     int64
 6   Seniority        20 non-null     object
dtypes: int64(4), object(3)
memory usage: 1.2+ KB

In [52]:
df.loc[df['YearsExperience']<3 , 'Salary'] = 35000

In [53]:
df.loc[df['YearsExperience']<3]

       Name  Age Department  Salary  YearsExperience  DeptCode Seniority
8    George   33      Sales   35000                0         1    Junior
11   George   48  Marketing   35000                0         2    Junior
18   Hannah   42      Sales   35000                2         1    Junior
19  Charlie   30       Tech   35000                2         4    Junior


# 6Ô∏è‚É£ Compare using .loc and .iloc to select the same row:
#    - Select the 3rd row using .iloc
#    - Find its index value and use .loc to select the same row by label

In [61]:
df.iloc[2]

Name                Ethan
Age                    45
Department           Tech
Salary             109479
YearsExperience        17
DeptCode                4
Seniority          Senior
Name: 2, dtype: object

In [62]:
label = df.index[2]
label

2

In [60]:
df.loc[label]

Name                Ethan
Age                    45
Department           Tech
Salary             109479
YearsExperience        17
DeptCode                4
Seniority          Senior
Name: 2, dtype: object


# 7Ô∏è‚É£ Check if there are any duplicate names in the dataset.
#    - If there are, show only those duplicated rows.

In [66]:
df[df['Name'].duplicated()]

       Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
3    George   51      Sales   59457               14         1     Senior
6     Ethan   42  Marketing  118953               14         2     Senior
7     Ethan   54  Marketing   92995               12         2     Senior
8    George   33      Sales   35000                0         1     Junior
10  Charlie   46      Sales   85758                8         1  Mid-level
11   George   48  Marketing   35000                0         2     Junior
12  Charlie   49       Tech  111211               11         4     Senior
13  Charlie   37       Tech  105697                7         4  Mid-level
14   Hannah   36         HR   77065               10         3     Senior
15    Ethan   24       Tech   72606               18         4     Senior
16    Diana   58         HR   51534               16         3     Senior
17   Hannah   28       Tech   80397                7         4  Mid-level
18   Hannah   42      Sales   35000                2         1     Junior
19  Charlie   30       Tech   35000                2         4     Junior


# 8Ô∏è‚É£ Sort the DataFrame by Salary in descending order.
#    - Then sort it by Department and within Department by Age.

In [72]:
df.sort_values('Salary', ascending=False).head()

       Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
6     Ethan   42  Marketing  118953               14         2     Senior
5    Hannah   23  Marketing  117189                8         2  Mid-level
12  Charlie   49       Tech  111211               11         4     Senior
2     Ethan   45       Tech  109479               17         4     Senior
1     Diana   23  Marketing  107121               12         2     Senior

In [76]:
df.sort_values(['Department','Age']).head()

      Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
14  Hannah   36         HR   77065               10         3     Senior
0   George   43         HR   75920               15         3     Senior
16   Diana   58         HR   51534               16         3     Senior
1    Diana   23  Marketing  107121               12         2     Senior
5   Hannah   23  Marketing  117189                8         2  Mid-level


# 9Ô∏è‚É£ Slice the DataFrame to return rows 5 through 12 and columns 'Name', 'Salary'
#    - Try slicing using both label-based and position-based methods.

In [78]:
df.loc[5:12, ['Name', 'Salary']]

       Name  Salary
5    Hannah  117189
6     Ethan  118953
7     Ethan   92995
8    George   35000
9       Bob   49692
10  Charlie   85758
11   George   35000
12  Charlie  111211

In [85]:
df.iloc[5:12, [df.columns.get_loc('Name'),df.columns.get_loc('Salary')]]

       Name  Salary
5    Hannah  117189
6     Ethan  118953
7     Ethan   92995
8    George   35000
9       Bob   49692
10  Charlie   85758
11   George   35000


# üîü Find all rows where the name starts with 'A' or 'D'.
#    - Use string methods with .str accessor.

In [88]:
df['Name'].unique()

array(['George', 'Diana', 'Ethan', 'Charlie', 'Hannah', 'Bob'],
      dtype=object)

In [93]:
df[df.loc[:, 'Name'].str.startswith(('D','A'))]

     Name  Age Department  Salary  YearsExperience  DeptCode Seniority
1   Diana   23  Marketing  107121               12         2    Senior
16  Diana   58         HR   51534               16         3    Senior

In [133]:
df[df.iloc[:, 0].str.startswith(('D','A'))]

     Name  Age Department  Salary  YearsExperience  DeptCode Seniority
1   Diana   23  Marketing  107121               12         2    Senior
16  Diana   58         HR   51534               16         3    Senior


# 1Ô∏è‚É£1Ô∏è‚É£ Drop all rows where Age is below 25.
#     - Explain whether this modifies the DataFrame in place or returns a copy.

In [101]:
df.drop(df[df['Age'] < 25].index)

       Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
0    George   43         HR   75920               15         3     Senior
2     Ethan   45       Tech  109479               17         4     Senior
3    George   51      Sales   59457               14         1     Senior
4   Charlie   59       Tech  106557               12         4     Senior
6     Ethan   42  Marketing  118953               14         2     Senior
7     Ethan   54  Marketing   92995               12         2     Senior
8    George   33      Sales   35000                0         1     Junior
9       Bob   43  Marketing   49692                6         2  Mid-level
10  Charlie   46      Sales   85758                8         1  Mid-level
11   George   48  Marketing   35000                0         2     Junior
12  Charlie   49       Tech  111211               11         4     Senior
13  Charlie   37       Tech  105697                7         4  Mid-level
14   Hannah   36         HR   77065               10         3     Senior
16    Diana   58         HR   51534               16         3     Senior
17   Hannah   28       Tech   80397                7         4  Mid-level
18   Hannah   42      Sales   35000                2         1     Junior
19  Charlie   30       Tech   35000                2         4     Junior

In [102]:
df.head()
# Drop without anything drops from acopy of the df if i want it to affect original either use the inplace parameter of assign the dropping to the df

      Name  Age Department  Salary  YearsExperience  DeptCode Seniority
0   George   43         HR   75920               15         3    Senior
1    Diana   23  Marketing  107121               12         2    Senior
2    Ethan   45       Tech  109479               17         4    Senior
3   George   51      Sales   59457               14         1    Senior
4  Charlie   59       Tech  106557               12         4    Senior


# 1Ô∏è‚É£2Ô∏è‚É£ Use groupby to calculate the average salary per Department.
#     - Bonus: Show the average age and average experience too.

In [103]:
df.groupby('Department')['Salary'].mean()

Department
HR           68173.000000
Marketing    86825.000000
Sales        53803.750000
Tech         88706.714286
Name: Salary, dtype: float64

In [105]:
df.groupby('Department')['Age'].mean()

Department
HR           45.666667
Marketing    38.833333
Sales        43.000000
Tech         38.857143
Name: Age, dtype: float64

In [106]:
df.groupby('Department')['YearsExperience'].mean()

Department
HR           13.666667
Marketing     8.666667
Sales         6.000000
Tech         10.571429
Name: YearsExperience, dtype: float64


# 1Ô∏è‚É£3Ô∏è‚É£ Use groupby to count how many employees are in each Department.

In [110]:
df.groupby('Department')['Name'].count()

Department
HR           3
Marketing    6
Sales        4
Tech         7
Name: Name, dtype: int64


# 1Ô∏è‚É£4Ô∏è‚É£ Use .apply to normalize the Salary column (min-max scaling between 0 and 1).
#     - Bonus: Write your own normalization function and pass it to apply.

In [111]:
def norm(x, maxi, mini):
  return (x - mini)/(maxi - mini)

In [112]:
df.describe()

             Age         Salary  YearsExperience   DeptCode
count  20.000000      20.000000        20.000000  20.000000
mean   40.700000   78081.550000         9.550000   2.650000
std    11.183164   30178.471336         5.548589   1.182103
min    23.000000   35000.000000         0.000000   1.000000
25%    32.250000   51073.500000         6.750000   2.000000
50%    42.500000   78731.000000        10.500000   2.500000
75%    48.250000  106698.000000        14.000000   4.000000
max    59.000000  118953.000000        18.000000   4.000000

In [115]:
mini = df['Salary'].min()
maxi = df['Salary'].max()
df['Salary'].apply(lambda x : norm(x, maxi, mini))

0     0.487416
1     0.859064
2     0.887151
3     0.291318
4     0.852346
5     0.978988
6     1.000000
7     0.690803
8     0.000000
9     0.175003
10    0.604600
11    0.000000
12    0.907782
13    0.842102
14    0.501054
15    0.447941
16    0.196944
17    0.540743
18    0.000000
19    0.000000
Name: Salary, dtype: float64


# 1Ô∏è‚É£5Ô∏è‚É£ Use boolean indexing to find all employees who:
#     - Are in 'HR' OR 'Tech', AND have > 5 years of experience.

# üîÅ For many of these tasks, try both .loc and .iloc to build intuition on their differences.

In [124]:
df.loc[((df['Department'] == 'HR' )| (df['Department']=='Tech'))
 &( df['YearsExperience']>5),:]

       Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
0    George   43         HR   75920               15         3     Senior
2     Ethan   45       Tech  109479               17         4     Senior
4   Charlie   59       Tech  106557               12         4     Senior
12  Charlie   49       Tech  111211               11         4     Senior
13  Charlie   37       Tech  105697                7         4  Mid-level
14   Hannah   36         HR   77065               10         3     Senior
15    Ethan   24       Tech   72606               18         4     Senior
16    Diana   58         HR   51534               16         3     Senior
17   Hannah   28       Tech   80397                7         4  Mid-level

In [132]:
cond = ((df['Department'] == 'HR' )| (df['Department']=='Tech'))&( df['YearsExperience']>5)
df.iloc[df[cond].index,:]

       Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
0    George   43         HR   75920               15         3     Senior
2     Ethan   45       Tech  109479               17         4     Senior
4   Charlie   59       Tech  106557               12         4     Senior
12  Charlie   49       Tech  111211               11         4     Senior
13  Charlie   37       Tech  105697                7         4  Mid-level
14   Hannah   36         HR   77065               10         3     Senior
15    Ethan   24       Tech   72606               18         4     Senior
16    Diana   58         HR   51534               16         3     Senior
17   Hannah   28       Tech   80397                7         4  Mid-level